[package]
name = "bugstalker"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Derevtsov Konstantin <godzie@yandex.ru>"]

[dependencies]
nix = "0.26.2"
once_cell = "1.13.1"
anyhow = "1.0"
rustyline = "11.0.0"
rustyline-derive = "0.8.0"
gimli = "0.27.3"
object = "0.31.1"
memmap2 = "0.7.1"
ouroboros = "0.15.4"
typed-arena = "2.0.1"
fallible-iterator = "0.2.0"
itertools = "0.10.3"
unwind = { version = "0.4.1", features = ["ptrace"] }
rustc-demangle = "0.1.21"
thiserror = "1.0.37"
bytes = "1.2.1"
log = "0.4.17"
env_logger = "0.9.3"
tui = "0.19"
tui-textarea = "*"
crossterm = "0.25"
clap =  { version = "4.0", features = ["derive"] }
uuid = {version = "1.2.2", features = ["v4", "fast-rng", "macro-diagnostics"]}
os_pipe = "1.1.2"
proc-maps = "0.3.0"
thread_db = "0.1.3"
smallvec = "1.10.0"
rand = "0.8.5"
ctrlc = "3.2.5"
nom = { version = "7.1.3", features = ["alloc"]}
nom-supreme = "0.8.0"
strum = "0.24"
strum_macros = "0.24"
signal-hook = "0.3.15"
rayon = "1.7.0"
trie-rs = "0.1.1"
regex = "1.8.4"
walkdir = "2.3.3"

[dev-dependencies]
sysinfo = "0.28.4"
serial_test = "1.0.0"

[features]
int_test = []
no_libunwind = []

[[bin]]
name = "hello_world"
test = false

[[bin]]
name = "calc"
test = false

[[bin]]
name = "vars"
test = false

[[bin]]
name = "mt"
test = false

[[bin]]
name = "recursion"
test = false

[[bin]]
name = "signals"
test = false